import re, os, sys, readline
sys.path.append("/coasiasemi/home/tientq/python_dir") 
sys.path.append("/coasiasemi/home/tientq/.local/lib/python3/site-packages") 
import tian_lib as tian
import random

import jinja2

list_word = [
	# Unit 1
	["co cong viec tot"                      ,"have a good job"                        ],
	["co nhieu ban be the co chu/lam."       ,"have so many friends"                   ],
	["con moi"                               ,"(be) still new"                         ],
	["da cu"                                 ,"(be) already old"                       ],
	["it ban"                                ,"few friends"                            ],
	["it thoi gian"                          ,"little time"                            ],
	["it tien"                               ,"little money"                           ],
	["kha moi"                               ,"quite new"                              ],
	["mot bac si gioi"                       ,"a good doctor"                          ],
	["mot co gai kha la tot"                 ,"a pretty good girl"                     ],
	["mot it tien"                           ,"a little money"                         ],
	["mot vai nguoi ban"                     ,"a few friends"                          ],
	["nhieu ban"                             ,"many friends /"                         ],
	["nhieu thoi gian ranh"                  ,"much free time"                         ],
	["nhieu tien"                            ,"much money"                             ],
	["noi duoc it tieng anh"                 ,"speak little English"                   ],
	["noi duoc mot it tieng anh"             ,"speak a little English"                 ],
	["noi tieng anh gioi"                    ,"speak good English/ speak English well" ],
	["o ha noi"                              ,"in Hanoi"                               ],
	["rat thich ca phe"                      ,"like coffee very much"                  ],
	["Tieng anh cua em kem"                  ,"My English is bad/poor."                ],
	["Toi la bac si. Anh cung la bac si."    ,"I’m a doctor. You are a doctor, too."   ],
	["Toi la bac si. Toi cung la giao vien." ,"I’m a doctor. I’m also a teacher."      ],
	["tren ban"                              ,"on the table"                           ],
	["ngoai san"                             ,"in the garden"                          ],

	# Unit 2
	[" mot nguoi nau an ngon"                       ," a good/great cook"                                                       ],
	[" luon o trong tam tri"                        ," (be) always in my mind"                                                  ],
	[" chua den 30 (tuoi)"                          ," under 30"                                                                ],
	[" o nha"                                       ," (be) at home"                                                            ],
	[" o cho lam"                                   ," (be) at work"                                                            ],
	[" do la mot mon qua"                           ," it is a gift"                                                            ],
	[" mot cuon tieu thuyet thu vi bang tieng anh." ," an interesting novel in english"                                         ],
	[" cho khong co duoi"                           ," dogs without a tail."                                                    ],
	[" khoe <co tinh trang suc khoe tot>"           ," (be) in good health"                                                     ],
	[" co tinh trang suc khoe kem <om yeu>"         ," (be) in bad health"                                                      ],
	[" no nan"                                      ," (be) in debt"                                                            ],
	[" gap rac roi/kho khan"                        ," (be) in difficulty"                                                      ],
	[" gap rac roi/kho khan"                        ," (be) in trouble"                                                         ],
	[" hay den som"                                 ," (be) often early/come early"                                             ],
	[" hay di muon"                                 ," (be) often late/come late"                                               ],
	[" 5 thang tuoi"                                ," 5 months old"                                                            ],
	[" cam on ban nhieu"                            ," a big/huge thanks to you"                                                ],
	[" bo dao nia"                                  ," a knife and folk"                                                        ],
	[" tam tuoi may`"                               ," about your age"                                                          ],
	[" buoi trua/toi"                               ," at noon/night"                                                           ],
	[" den day"                                     ," come here"                                                               ],
	[" kinh doanh"                                  ," do business"                                                             ],
	[" nau com"                                     ," do the cooking"                                                          ],
	[" rua bat"                                     ," do the dishes/wash dishes"                                               ],
	[" lai xe di lam"                               ," drive to work"                                                           ],
	[" toi do"                                      ," go there"                                                                ],
	[" di ngu"                                      ," go to bed"                                                               ],
	[" di london"                                   ," go to London"                                                            ],
	[" di lam"                                      ," go to work"                                                              ],
	[" di lam vao cn"                               ," go to work on sunday"                                                    ],
	[" an ba bua"                                   ," have 3 meals a day"                                                      ],
	[" tam"                                         ," have a bath"                                                             ],
	[" an bua sang/ trua/ toi"                      ," have breakfast/lunch/dinner"                                             ],
	[" giup nhau"                                   ," help each other"                                                         ],
	[" sang/trua/toi"                               ," in the morning/afternoon/evening"                                        ],
	[" biet nhau ro"                                ," know each other well"                                                    ],
	[" song o nuoc ngoai"                           ," live abroad"                                                             ],
	[" ket ban"                                     ," make friends"                                                            ],
	[" don giuong`"                                 ," make the bed"                                                            ],
	[" Cam on anh nhieu"                            ," Many thanks"                                                             ],
	[" Dan ong xay nha, dan ba xay to am."          ," Men make houses, women make homes"                                       ],
	[" hay cung nhau den nha chung toi"             ," often come to our house together"                                        ],
	[" cong tac"                                    ," on business"                                                             ],
	[" di xe dap di lam"                            ," ride to work/ride my bike to work/ride to work on my bike/bike to work." ],
	[" tam nuoc lanh"                               ," take a cold shower ngay"                                                 ],
	[" ngu trua/chop mat"                           ," take a nap"                                                              ],
	[" tam"                                         ," take a shower"                                                           ],
	[" di bo."                                      ," take a walk"                                                             ],
	[" Cam on anh cho em di nho."                   ," Thank you for the ride."                                                 ],
	[" Cam on anh giup em."                         ," Thank you for your help"                                                 ],
	[" Cam on anh cho em muon tien."                ," Thank you for your money"                                                ],
	[" Cam on anh nhieu"                            ," Thank you very much"                                                     ],
	[" cuon sach nam tren ban"                      ," the book on the table"                                                   ],
	[" Nha <vo chong, anh chi> smith."              ," The Smiths"                                                              ],
	[" Co <liet ke-chi su ton tai>"                 ," There is/are N-sing/pl"                                                  ],
	[" hom nay em ban."                             ," Today, I'm busy."                                                        ],
	[" di bo di lam"                                ," walk to work"                                                            ],
	[" lam o cong ty tu nhan"                       ," work at a private company"                                               ],
	[" lam ban dem"                                 ," work at night"                                                           ],
	[" lam viec vao Chu Nhat"                       ," work on Sunday"                                                          ],

	# Unit 3
	["ban` tra"                                 ,"a tea table"                               ],
	["can giup do"                              ,"(be) in need of help"                      ],
	["Chi danh cho nguoi lon."                  ,"Adults only"                               ],
	["Chi la dua con nit."                      ,"an only kid"                               ],
	["chi quanh day thoi"                       ,"just around here"                          ],
	["Chuyen nay chi tao voi may biet."         ,"This is just between you and me."          ],
	["co gai rat dep/co gai co ve dep long lay" ,"a girl of great beauty"                    ],
	["con cho nha Black"                        ,"The Black's dog"                           ],
	["con mot"                                  ,"only a kid"                                ],
	["cong viec vat va"                         ,"hard work"                                 ],
	["Do thuc su la mot van de kho."            ,"It's really a difficult problem."          ],
	["doi giay nay"                             ,"These shoes"                               ],
	["giao vien (day) tieng anh"                ,"a teacher of English- an English teacher"  ],
	["khong phan su mien vao"                   ,"Staff only"                                ],
	["kien thuc tieng anh cua toi"              ,"My knowledge of English"                   ],
	["lam viec cham chi."                       ,"work hard"                                 ],
	["Mot cau tra loi thu vi."                  ,"an interesting answer"                     ],
	["Mot kien thuc tieng Anh vung vang."       ,"a good knowledge of English."              ],
	["mot ngay dai lam viec vat va"             ,"a long day of hard work"                   ],
	["nghi giai lao uong ca phe"                ,"take a coffee break / have a coffee break" ],
	["ngoi nha cua em gai toi"                  ,"the house of my sister /my sister's house" ],
	["nguoi phu nu do"                          ,"that woman"                                ],
	["nguoi phu nu nay"                         ,"this woman"                                ],
	["noi chi tieng Anh thoi"                   ,"speak only English"                        ],
	["o tren cai the gioi rong lon nay"         ,"in this big world"                         ],
	["rat thoai mai"                            ,"very comfortable"                          ],
	["tach uong tra"                            ,"a tea cup"                                 ],
	["tap 2 tieng Yoga"                         ,"do 2 hours yoga"                           ],
	["tham chi/ngay ca vao mua dong"            ,"even in winter"                            ],
	["The thi tuyet"                            ,"That's good/nice/great"                    ],
	["trong mat me toi <cai nhin>"              ,"in my mother's eyes."                      ],
	["viec hoc tieng anh"                       ,"The study of English"                      ],
	["Day la Tom, ban toi."						     ,"This is Tom, my friend."                   ],
	["duoc chon tra, ca phe hoac sua"           ,"have a choice of  tea, coffee, or milk"    ],
]

while (1):
	var_rand = random.randint(0, len(list_word)-1);
	tian.print_banner(f"{list_word[var_rand][0]}")

	if (input(">>>") == 'exit()'):
		exit()
	print(f"    {tian.BLUE}{list_word[var_rand][1]}{tian.RESET}\n")
	


